"""
Plant Disease Prediction API Router
=====================================
Endpoint:
  POST /api/disease/predict  — accepts a multipart image upload and returns
  the predicted disease label, confidence score, and treatment recommendation.

The classifier uses a MobileNetV2 CNN trained on the PlantVillage dataset
(see models/train_plantvillage_cnn.py).  For best results, ensure the .pth
model file has been generated by running the training script first.
"""

from fastapi import APIRouter, File, UploadFile, HTTPException
from pydantic import BaseModel
from typing import Optional
import json
import numpy as np
import os
import io
import base64
import cv2
from chatbot.translator import translate_text

try:
    from PIL import Image
except ImportError:
    raise RuntimeError("Pillow is required: pip install Pillow")

try:
    import torch
    import torch.nn as nn
    from torchvision import models, transforms
    from torchvision.models import MobileNet_V2_Weights
    
    # 🔴 CRITICAL FOR RENDER: 🔴
    # Limit number of CPU threads to 1 to drastically reduce 
    # memory allocated for PyTorch's OpenMP thread pools.
    torch.set_num_threads(1)
    
    _TORCH_AVAILABLE = True
except ImportError:
    _TORCH_AVAILABLE = False

disease_router = APIRouter()

# ── Constants ─────────────────────────────────────────────────────────────────
_BASE       = os.path.join(os.path.dirname(__file__), "..", "models")
_MODEL_PATH = os.path.join(_BASE, "disease_model_cnn.pth")
_LABELS_PATH = os.path.join(_BASE, "disease_class_labels.json")
_TREATMENT_PATH = os.path.join(_BASE, "disease_treatment_map.json")

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

# ── Load model ────────────────────────────────────────────────────────────────

_model     = None
_labels    = {}
_treatments = {}
_device    = None
_img_size  = 224

if not _TORCH_AVAILABLE:
    print("⚠ PyTorch not installed. Disease prediction will be unavailable.")
elif not os.path.exists(_MODEL_PATH):
    print(f"⚠ CNN model not found at {_MODEL_PATH}. "
          "Run models/train_plantvillage_cnn.py to generate it.")
else:
    try:
        _device = (
            torch.device("cuda") if torch.cuda.is_available()
            else torch.device("mps") if hasattr(torch.backends, "mps") and torch.backends.mps.is_available()
            else torch.device("cpu")
        )
        checkpoint   = torch.load(_MODEL_PATH, map_location=_device, weights_only=False)
        class_names  = checkpoint["class_names"]
        num_classes  = checkpoint["num_classes"]
        _img_size    = checkpoint.get("img_size", 224)

        # Re-build the exact same head used during training
        _cnn = models.mobilenet_v2(weights=MobileNet_V2_Weights.IMAGENET1K_V1)
        in_features = _cnn.classifier[1].in_features
        _cnn.classifier = nn.Sequential(
            nn.Dropout(p=0.3),
            nn.Linear(in_features, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(p=0.2),
            nn.Linear(256, num_classes),
        )
        _cnn.load_state_dict(checkpoint["model_state_dict"])
        _cnn = _cnn.to(_device)
        _cnn.eval()

        _model = _cnn
        print(f"✓ CNN disease model loaded ({num_classes} classes) on {_device}")
    except Exception as exc:
        print(f"⚠ Could not load CNN model: {exc}")

try:
    with open(_LABELS_PATH) as f:
        _labels = json.load(f)   # {"0": "ClassName", ...}
    print("✓ Disease class labels loaded")
except Exception as e:
    print(f"⚠ Could not load disease labels: {e}")

try:
    with open(_TREATMENT_PATH) as f:
        _treatments = json.load(f)
    print("✓ Disease treatment map loaded")
except Exception as e:
    print(f"⚠ Could not load treatment map: {e}")


# ── Image preprocessing ───────────────────────────────────────────────────────

_preprocess = transforms.Compose([
    transforms.Resize((_img_size, _img_size)),
    transforms.ToTensor(),
    transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
]) if _TORCH_AVAILABLE else None


def _preprocess_image(image_bytes: bytes) -> tuple["torch.Tensor", "Image.Image"]:
    """Convert raw image bytes to a preprocessed tensor batch and return the original PIL image."""
    img = Image.open(io.BytesIO(image_bytes)).convert("RGB")
    img_resized = img.resize((_img_size, _img_size))
    tensor = _preprocess(img)           # (3, H, W)
    return tensor.unsqueeze(0), img_resized          # (1, 3, H, W), PIL Image


# ── Response schema ───────────────────────────────────────────────────────────

class DiseasePredictionResponse(BaseModel):
    disease:         str
    treatment:       str
    heatmap_image:   Optional[str] = None
    all_predictions: Optional[list] = None

# ── Grad-CAM Helper ───────────────────────────────────────────────────────────

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None
        self.forward_handle = self.target_layer.register_forward_hook(self.save_activation)
        self.backward_handle = self.target_layer.register_full_backward_hook(self.save_gradient)

    def remove_hooks(self):
        if hasattr(self, 'forward_handle') and self.forward_handle:
            self.forward_handle.remove()
        if hasattr(self, 'backward_handle') and self.backward_handle:
            self.backward_handle.remove()

    def save_activation(self, module, input, output):
        self.activations = output.detach()

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0].detach()

    def generate(self, input_tensor, target_class):
        self.model.zero_grad()
        output = self.model(input_tensor)
        target = output[0, target_class]
        target.backward()

        pooled_gradients = torch.mean(self.gradients, dim=[0, 2, 3])
        for i in range(self.activations.shape[1]):
            self.activations[:, i, :, :] *= pooled_gradients[i]

        heatmap = torch.mean(self.activations, dim=1).squeeze()
        heatmap = torch.nn.functional.relu(heatmap)
        heatmap /= torch.max(heatmap)
        return heatmap.cpu().numpy()


# ── Endpoints ─────────────────────────────────────────────────────────────────

@disease_router.post("/predict", response_model=DiseasePredictionResponse)
async def predict_disease(file: UploadFile = File(...), lang: str = "en"):
    """
    Upload a leaf image (JPEG / PNG) and receive a plant disease prediction.

    - **file**: The leaf image file.
    """
    if _model is None or not _labels:
        raise HTTPException(
            status_code=503,
            detail=(
                "Disease prediction model is not available. "
                "Run models/train_plantvillage_cnn.py to generate the model files."
            )
        )

    if not file.content_type.startswith("image/"):
        raise HTTPException(
            status_code=400,
            detail=f"Invalid file type '{file.content_type}'. Please upload an image file."
        )

    try:
        image_bytes = await file.read()
        tensor, original_img = _preprocess_image(image_bytes)
        tensor = tensor.to(_device)
        tensor.requires_grad = True
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Could not process image: {e}")

    try:
        # We need gradients for Grad-CAM
        logits = _model(tensor)                  # (1, num_classes)
        proba  = torch.softmax(logits, dim=1)[0] # (num_classes,)

        proba_np  = proba.detach().cpu().numpy()
        top_idx   = int(np.argmax(proba_np))

        disease_label = _labels.get(str(top_idx), "Unknown")
        treatment     = _treatments.get(disease_label, "Consult a local agricultural extension officer.")

        # Generate Grad-CAM Heatmap
        heatmap_b64 = None
        try:
            target_layer = _model.features[-1]
            cam = GradCAM(_model, target_layer)
            heatmap = cam.generate(tensor, top_idx)

            heatmap_resized = cv2.resize(heatmap, (original_img.width, original_img.height))
            heatmap_resized = np.uint8(255 * heatmap_resized)
            heatmap_colored = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)

            original_cv = cv2.cvtColor(np.array(original_img), cv2.COLOR_RGB2BGR)
            overlayed = cv2.addWeighted(original_cv, 0.5, heatmap_colored, 0.5, 0)
            overlayed_rgb = cv2.cvtColor(overlayed, cv2.COLOR_BGR2RGB)

            final_img = Image.fromarray(overlayed_rgb)
            buffered = io.BytesIO()
            final_img.save(buffered, format="JPEG")
            heatmap_b64 = "data:image/jpeg;base64," + base64.b64encode(buffered.getvalue()).decode("utf-8")
        except Exception as cam_err:
            print(f"Grad-CAM generation failed: {cam_err}")
        finally:
            if 'cam' in locals():
                cam.remove_hooks()

        # Top-3 predictions
        top3_indices = np.argsort(proba_np)[::-1][:3]
        top3 = [
            {
                "disease":    translate_text(_labels.get(str(int(i)), "Unknown"), "en", lang)
            }
            for i in top3_indices
        ]

        return DiseasePredictionResponse(
            disease=translate_text(disease_label, "en", lang),
            treatment=translate_text(treatment, "en", lang),
            heatmap_image=heatmap_b64,
            all_predictions=top3,
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Prediction error: {e}")
    finally:
        import gc
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()


@disease_router.get("/classes")
async def get_disease_classes():
    """Return all supported disease classes."""
    return {"classes": list(_labels.values())}
